@extends('layouts.app')
@section('title', 'Violations and Settlements')
@section('content')
<section class="card mb-3"><form method="GET" class="row g-3 p-3">
<div class="col-md-4"><label class="form-label" for="recordSearch">Citizen name or plate</label><input id="recordSearch" name="search" class="form-control" maxlength="255" value="{{ request('search') }}"></div>
<div class="col-md-4"><label class="form-label" for="recordStatus">Settlement status</label><select id="recordStatus" name="status" class="form-select"><option value="">All statuses</option>@foreach(['pending'=>'Not Yet Verified','settled'=>'Settled','dismissed'=>'Dismissed'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label" for="recordType">Offense (includes historical records)</label><select id="recordType" name="type" class="form-select"><option value="">All offenses</option>@foreach($violationTypes as $type)<option value="{{ $type->id }}" @selected(request('type') == $type->id)>{{ $type->category }} — {{ $type->offense_name }}{{ $type->trashed() ? ' (retired)' : '' }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label" for="dateFrom">Apprehension date from</label><input id="dateFrom" type="date" name="date_from" class="form-control" value="{{ request('date_from') }}"></div>
<div class="col-md-4"><label class="form-label" for="dateTo">Apprehension date to</label><input id="dateTo" type="date" name="date_to" class="form-control" value="{{ request('date_to') }}"></div>
<div class="col-md-4"><label class="form-label" for="verificationQueue">Verification queue</label><select id="verificationQueue" name="payment_status" class="form-select"><option value="">All records</option>@foreach(['unpaid'=>'Awaiting verification (all)','ready'=>'Ready to verify','paid'=>'Settled','overdue'=>'Past verification due date','needs_review'=>'Amount needs review'] as $value=>$label)<option value="{{ $value }}" @selected(request('payment_status')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12 d-flex gap-2"><button class="btn btn-primary">Apply filters</button><a href="{{ route('violations.index') }}" class="btn btn-outline-secondary">Clear filters</a></div>
</form></section>
<div class="d-md-none">@forelse($violations as $v)
<article class="card p-3 mb-3"><strong class="text-break">{{ $v->personDetail('full_name') }}</strong><p class="my-2">{{ $v->violationType?->offense_name }}</p><p><span class="badge badge-{{ $v->status }}">{{ $v->payment_label }}</span></p><p class="small text-muted">#{{ $v->id }} · {{ $v->violation_date->format('M j, Y') }} · {{ $v->citation?->fine_label ?? 'Amount needs review' }}</p><a href="{{ route('violations.show', $v) }}" class="btn btn-outline-primary">View and review settlement</a></article>
@empty<p class="card p-3">No records match these filters.</p>@endforelse</div>
<section class="card d-none d-md-block"><div class="table-responsive"><table class="table mb-0"><thead><tr><th scope="col">Citizen / reference</th><th scope="col">Offense</th><th scope="col">Settlement</th><th scope="col">Action</th><th scope="col">Fine</th><th scope="col">Apprehension date</th></tr></thead><tbody>
@forelse($violations as $v)<tr><td><strong class="text-break">{{ $v->personDetail('full_name') }}</strong><div class="small text-muted">#{{ $v->id }}{{ $v->personDetail('vehicle_plate') ? ' · '.$v->personDetail('vehicle_plate') : '' }}</div></td><td>{{ $v->violationType?->offense_name }}</td><td><span class="badge badge-{{ $v->status }}">{{ $v->payment_label }}</span>@if($v->citation?->fine_amount === null)<div class="small text-muted">Amount needs review</div>@endif</td><td><a href="{{ route('violations.show', $v) }}" class="btn btn-outline-primary btn-sm" aria-label="Review violation {{ $v->id }}">View / review</a></td><td>{{ $v->citation?->fine_label ?? 'Not configured' }}</td><td class="text-nowrap">{{ $v->violation_date->format('M j, Y') }}</td></tr>
@empty<tr><td colspan="6">No records match these filters.</td></tr>@endforelse
</tbody></table></div></section><div class="mt-3">{{ $violations->links() }}</div>
@endsection
